version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "main"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci(deps)"
    target-branch: "main"
