<?php
/**
 * This file is licensed under MIT License.
 *
 * Copyright (c) 2024 Ibrahim BinAlshikh
 *
 * For more information on the license, please visit:
 * https://github.com/WebFiori/.github/blob/main/LICENSE
 *
 */
namespace webfiori\cli;

use PHPUnit\Framework\TestCase;

/**
 * Helper class which is used to write unit test cases for command line commands.
 *
 * @author Ibrahim
 */
class CommandTestCase extends TestCase {
    /**
     * End of line character which is used when sending outputs.
     */
    const NL = "\n";
    private $exitStatus;
    private $outputs;
    /**
     * 
     * @var Runner
     */
    private $runner;
    /**
     * Register multiple commands and simulate the process of executing the app
     * as if in production environment.
     * 
     * @param array $argv An array that represents arguments vector. The array
     * can be indexed or associative. If associative, the key will represent
     * an option and the value of the key will represent its value. First
     * index should contain the name of the command that will be executed from
     * the registered commands.
     * 
     * @param array $userInputs An array that holds user inputs. Each index
     * should hold one line that represent an input to specific prompt.
     * 
     * @param array $commands An array that holds objects of type 'CLICommand'.
     * Each object represents the registered command.
     * 
     * @param string $default A string that represents the name of the command
     * that will get executed by default if no command name is provided
     * in arguments victor.
     * 
     * @return array The method will return an array of strings that represents
     * the output of execution.
     */
    public function executeMultiCommand(array $argv = [], array $userInputs = [], array $commands = [], string $default = '') : array {
        $runner = $this->getRunner(true);

        foreach ($commands as $command) {
            $runner->register($command);
        }
        $runner->setDefaultCommand($default);
        $this->exec($argv, $userInputs);

        return $this->getOutput();
    }
    /**
     * Executes a specific command and return its output as an array.
     * 
     * @param CLICommand $command The command that will be tested.
     * 
     * @param array $argv Arguments vector that will be passed to the command.
     * This can be an associative array of options and values or just options.
     * 
     * @param array $userInputs A sequence of strings that represents user inputs
     * when the command is executing. Each index in the array represents a single
     * line of input.
     * 
     * @return array The method will return an array that will hold
     * outputs line by line in each index.
     */
    public function executeSingleCommand(CLICommand $command, array $argv = [], array $userInputs = []) : array {
        $this->getRunner(true)->register($command);
        $this->exec($argv, $userInputs, $command);

        return $this->getOutput();
    }
    /**
     * Returns an integer thar represents exit status of running specific command.
     * 
     * @return int Default return value is 0.
     */
    public function getExitCode() : int {
        if ($this->exitStatus === null) {
            $this->exitStatus = 0;
        }

        return $this->exitStatus;
    }
    /**
     * Returns an array that holds all outputs that was generated by running specific
     * command.
     * 
     * @return array If no command was executed, the array will be empty. Other
     * than that, the array will hold outputs line by line in each index.
     */
    public function getOutput() : array {
        if ($this->outputs === null) {
            $this->outputs = [];
        }

        return $this->outputs;
    }
    /**
     * Returns the instance that the class is using to execute the commands.
     * 
     * @param bool $reset If set to true, input stream, output stream and, 
     * registered commands of the runner will reset to default.
     * 
     * @return Runner The instance that the class is using to execute the commands.
     */
    public function getRunner(bool $reset = false) : Runner {
        if ($this->runner === null) {
            $this->runner = new Runner();
        }

        if ($reset) {
            $this->runner->reset();
        }

        return $this->runner;
    }
    /**
     * Sets a custom runner to use in test execution.
     * 
     * @param Runner $runner
     * 
     * @return CommandTestCase The method will return same instance at which
     * the method is called from.
     */
    public function setRunner(Runner $runner) : CommandTestCase {
        $this->runner = $runner;
    }
    private function exec(array $argv, array $userInputs, ?CLICommand $command = null) {
        if ($command !== null) {
            $key = array_search($command->getName(), $argv);

            if ($key != 0 || $key === false) {
                $argv = array_merge(['main.php', $command->getName()], $argv);
            } else {
                $argv = array_merge(['main.php'], $argv);
            }
        } else {
            $argv = array_merge(['main.php'], $argv);
        }
        $runner = $this->getRunner();

        //Set arguments vector
        $runner->setArgsVector($argv);

        //Set user inputs.
        //Must be called to use Array as input and output stream even if there are no inputs.
        $runner->setInputs($userInputs);

        //Start the process
        $this->exitStatus = $runner->start();

        $this->outputs = $runner->getOutput();
    }
}
