name: Build PHP 8.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [ 8.0 ]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:8.5.13
          
     
      
      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
        
      - name: Execute Tests
        run: phpunit --configuration tests/phpunit.xml
      
      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}   
