name: Build PHP 8.3

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 

    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [8.3]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:9.5.20, composer

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-dev
      
      - name: Execute Tests
        run: phpunit --configuration tests/phpunit.xml
        
      - name: CodeCov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
    release_staging:
      name: Prepare Beta Release Branch / Publish Release
      needs:
        - "test"
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dev'
      steps:
        - uses: actions/checkout@v4
        - uses: google-github-actions/release-please-action@v4
          with:
            release-type: php
            target-branch: dev
            config-file: release-please-config.json
            token: ${{ secrets.GITHUB_TOKEN }}

    release_prod:
      name: Prepare Production Release Branch / Publish Release
      needs:
        - "test"
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'
      steps:
        - uses: actions/checkout@v4
        - uses: google-github-actions/release-please-action@v4
          with:
            release-type: php
            target-branch: main
            config-file: release-please-config.json
            token: ${{ secrets.GITHUB_TOKEN }}
